#!/bin/bash
REPEAT=100
if [ "$#" == "0" ]; then
echo "./run-nk DIR ell1 ell2 ... ellN"
exit 1
fi
DIR=$1
mkdir $DIR
while [ $# -gt  1 ]
do
    for (( i=1; $i<=$REPEAT; i=$i+1 ))
    do
        NUM=`echo $i | awk '{printf "%03d", $1}'`
        ELL=$2
        nohup nice -n19 ./DSMGA2 $ELL 6 10000 -1 1 1 -1 $i > ./$DIR/$ELL-$NUM &
        echo "Submitting $ELL-$NUM"
        sleep 2
        TT=$(ps -xaf | grep DSMGA2 | wc -l)
        while [ $TT -gt 4 ]
        do
            sleep 1
            TT=$(ps -xaf | grep DSMGA2 | wc -l)
        done
    done
    shift
done
